#! /bin/sh
##
## $Id$
##
## Create the documents from sgml source. Please *only* call this
## script from top level makefile!

cd "$1"

if [ "$?" != "0" ]
then
	echo "ERROR: Can't change to directory '$1'..."
        exit 5
fi

echo -n "$1: "

sgml2txt -l vbox.sgml.in

if [ "$?" = "0" ]
then
	mv vbox.sgml.in.txt vbox.txt.in

	if [ "$?" != "0" ]
	then
		echo "ERROR: Can't move '$1/vbox.sgml.in.txt' to '$1/vbox.txt.in'."
		exit 5
	fi
else
	echo "ERROR: Can't create '$1/vbox.sgml.in.txt'."
	exit 5
fi

exit 0
